package com.kazhuga.swift.demo;

import com.kazhuga.swift.core.SwiftMessage;
import com.kazhuga.swift.generator.SwiftGenerator;
import com.kazhuga.swift.parser.SwiftParser;

/**
 * Demonstrates all five message types generated by this library.
 *
 * Run with:
 *   javac -d out $(find src -name "*.java")
 *   java -cp out com.kazhuga.swift.demo.SwiftDemo
 */
public class SwiftDemo {

    private static final SwiftGenerator GENERATOR = new SwiftGenerator();
    private static final SwiftParser    PARSER     = new SwiftParser();

    public static void main(String[] args) {
        printSeparator("SWIFT FIN Message Generator – Demonstration  [com.kazhuga.swift]");

        demoMT103();
        demoMT202();
        demoMT202COV();
        demoMT940();
        demoMT950();
        demoRoundTrip();

        System.out.println("\nAll messages generated successfully.");
    }

    // =========================================================================

    private static void demoMT103() {
        printSeparator("MT103 – Single Customer Credit Transfer");
        SwiftMessage msg = GENERATOR.generateMT103(SampleDataFactory.sampleMT103());
        System.out.println(msg.toPrettyString());
        System.out.println("── Wire Format ──────────────────────────────────────");
        System.out.println(msg.toSwiftString());
    }

    private static void demoMT202() {
        printSeparator("MT202 – Financial Institution Transfer");
        SwiftMessage msg = GENERATOR.generateMT202(SampleDataFactory.sampleMT202());
        System.out.println(msg.toPrettyString());
        System.out.println("── Wire Format ──────────────────────────────────────");
        System.out.println(msg.toSwiftString());
    }

    private static void demoMT202COV() {
        printSeparator("MT202COV – Cover Payment");
        SwiftMessage msg = GENERATOR.generateMT202COV(SampleDataFactory.sampleMT202COV());
        System.out.println(msg.toPrettyString());
        System.out.println("── Wire Format ──────────────────────────────────────");
        System.out.println(msg.toSwiftString());
    }

    private static void demoMT940() {
        printSeparator("MT940 – Customer Statement");
        SwiftMessage msg = GENERATOR.generateMT940(SampleDataFactory.sampleMT940());
        System.out.println(msg.toPrettyString());
        System.out.println("── Wire Format ──────────────────────────────────────");
        System.out.println(msg.toSwiftString());
    }

    private static void demoMT950() {
        printSeparator("MT950 – Bank Statement (Nostro Reconciliation)");
        SwiftMessage msg = GENERATOR.generateMT950(SampleDataFactory.sampleMT950());
        System.out.println(msg.toPrettyString());
        System.out.println("── Wire Format ──────────────────────────────────────");
        System.out.println(msg.toSwiftString());
    }

    private static void demoRoundTrip() {
        printSeparator("Round-Trip: Generate → Parse → Verify");
        try {
            SwiftMessage original = GENERATOR.generateMT103(SampleDataFactory.sampleMT103());
            String wire = original.toSwiftString();

            SwiftMessage parsed = PARSER.parse(wire);

            String orig32A   = original.getFieldValue("32A");
            String parsed32A = parsed.getFieldValue("32A");

            System.out.println("Original  Field 32A : " + orig32A);
            System.out.println("Re-parsed Field 32A : " + parsed32A);
            System.out.println("Round-trip match    : " + (orig32A != null && orig32A.equals(parsed32A)));

        } catch (Exception e) {
            System.err.println("Round-trip error: " + e.getMessage());
        }
    }

    private static void printSeparator(String title) {
        String line = "═".repeat(62);
        System.out.println("\n" + line);
        System.out.println("  " + title);
        System.out.println(line);
    }
}
